### ISSUE TITLE
Handle comments and footnotes in Text Fabric

### ISSUE THREAD

**Issue by hvlaardingerbroek** [CambridgeSemiticsLab/nena_tf#12]
Comments and footnotes are now ignored in the conversion to Text Fabric.

Should they be encoded, and if so, how?

Footnotes could be a feature of the preceding word, or character.

Generic comments such as `[interruption]` could be encoded as part of the text (as foreign word?), with feature `comment`?

Comments introducing change of speaker such as `[GK: ...]` could be encoded as part of the text, and the enclosed Aramaic text with special feature `speaker`?

If comments are part of the text, is that also true for the brackets? Should they be stored in another feature? Closing brackets maybe in the `trailer` feature, opening brackets in a `prefix` feature?

**Comment by codykingham** [comment]
Footnotes are now currently stashed as a feature of morphemes. Comments are included within the body of the text, but with a `speaker` feature. All other morphemes in the text have now received a speaker feature harvested from the `informant` metadata. But we still need to think through whether putting footnotes on morphemes makes sense. I feel like not! Will leave open until a solution presents itself.

**Comment by codykingham** [comment]
This issue will now be handled in the larger discussion on simplifying corpus features in issue #17
