### ISSUE TITLE
Text Fabric search

### ISSUE THREAD

**Issue by Paul32N** [CambridgeSemiticsLab/nena_tf#15]
Text Fabric Regex search function ignores hyphen -.
Hyphen is visible and informative in original text, e.g. qam-tara, qam-axlile
Hyphen should be included as a character to make searches easier

**Comment by codykingham** [comment]
Done. To access the updated data, run Text-Fabric in the following way:

```
text-fabric nena checkout=hot
```

After doing so, the new data should be downloaded. From then on, you can just invoke the regular ole:

```
text-fabric nena
```
