### ISSUE TITLE
Fuzzy searches in Text Fabric transcription lite

### ISSUE THREAD

**Issue by Paul32N** [CambridgeSemiticsLab/nena_tf#16]
Situation: 
Transcription lite splits up consonants with diacritics into two elements. Regex searches for consonants require more elements/characters than simple consonants. Vowels, on the other hand, are without accents in the lite transcription.

Problem: 
This makes searching for consonantal patterns/templates more difficult, because the original text based on the grammatical description treats all consonants as one segment/character set. 

Suggested solution: 
Perhaps we should delete all diacritic information for consonants in the lite transcription to allow for easy searches just as has already been done for the vowels without accents.

**Comment by codykingham** [comment]
Done. `trans_l` (transcription lite) now normalizes consonants by ignoring additional diacritical markers. This means that, e.g., 

```
ṃ = m
```

But also:
```
š = s
```

Perhaps this is TOO "light". If so, then what we need to do is decide which consonants should loose their diacritical marks. Let me know if you find this to be the case and I can give you guys a character sheet to mark with the correct lite transcription.
