### ISSUE TITLE
Preprocessing and UrmiBarwar

### ISSUE THREAD

**Issue by codykingham** [CambridgeSemiticsLab/nena_tf#2]
Can we combine preprocessing.ipynb and UrmiBarwar.ipynb? Is it useful to keep both to document our exploratory analysis?

**Comment by hvlaardingerbroek** [comment]
I kept them to document our steps, but that is not necessary. I think they are both obsolete -- if we add the introductory text of Preprocessing to the beginning of generate_TF we could remove them.

**Comment by hvlaardingerbroek** [comment]
I added the introductory text to generate_TF (https://github.com/CambridgeSemiticsLab/nena_corpus/commit/6da51c6ac7f7bdb2cdad1811fa2ef9601e05f7cb). Is there anything else in either  Preprocessing.ipynb or UrmiBarwar.ipynb? Otherwise I think we can delete them.

**Comment by codykingham** [comment]
Removed them in branch `new`. Will merge when done making edits.
Update: removed in https://github.com/CambridgeSemiticsLab/nena_corpus/commit/347692f3e97298e839fb561fc58d0f9b9c7bebb4
