### ISSUE TITLE
versioning and synchronization with corpus

### ISSUE THREAD

**Issue by codykingham** [CambridgeSemiticsLab/nena_tf#24]
[In conversation with @dirkroorda]

I've gone back and forth about the best way to version the text corpus. Since things have been in flux so much, I decided to lump everything under the `alpha` label. `alpha` is intended to be a non-stable, always-changing version—akin to the ETCBC's version `c` of the BHSA (https://github.com/ETCBC/bhsa/tree/c84c4f9d421f93363706c4d837dfbe27467b96c5/tf/c)

I have a number of questions, though, about the best way forward.

1. What should be the relationship between the versioning of the NENA corpus (the source files stored in https://github.com/CambridgeSemiticsLab/nena_corpus) and the TF versions. The conversion to TF derives a number of things (e.g. sentences) by passing over the data that are not directly in the source data. So updates to the TF that do not affect the corpus data are possible. Yet, how to keep these two things mutually intelligble?
2. Is it too early to produce a `v.1.0` version? Much is changing, an rapidly. We have to balance 1. keeping a good record of the changes made over time, but 2. avoiding over-clogging the versions with a bunch of trivial changes.

**Comment by dirkroorda** [comment]
Like in the bhsa: the corpus producer names versions (4, 4b, 2017).
A text-fabric dataset is based on such a version.
But the github repo in which the tf dataset is being maintained can go through releases and commits.
Each release may include any number of corpus versions.

So, back to NENA: if NENA defines version alpha, we also have an alpha version in TF. If we have TF specific updates, we can release them successively, still sticking to alpha.

**Comment by codykingham** [comment]
This is a great solution! Let's follow that convention. Thanks!

**Comment by codykingham** [comment]
Meant to close the versioning issue. Let's keep this pipeline issue open for now.
