### ISSUE TITLE
Add Prosaic Unit Objects

### ISSUE THREAD

**Issue by codykingham** [CambridgeSemiticsLab/nena_tf#4]
Pursuant to a conversation with Geoffrey, I would be nice if prosaic units are modeled as objects in the database. That is, basically, segments separated with `|`. Note that these segments can, but do not always, align with a formal syntactic unit, such as words or sentences. Since prosaic units are important/interesting from a research standpoint, having them as individual objects would make for some nice querying possibilities.

This would give the database the following structure:

```
text
    paragraph
        line
            sentence
                subsentence
                prosa
                    word
                        morpheme
                            char
```

Note that the `prosa` object is different from the others, since it might sometimes be larger than or smaller than the units listed above or below it here. That is due to its nature as a semantic rather than syntactic object.

**Comment by hvlaardingerbroek** [comment]
I agree. I have thought about implementing this, but as I was not entirely sure I have left it as it was so far.
Although you do say that prosaic units do not necessarily align with other syntactic units, I do think they *must* always align with words, am I not right? The word being the unit that is stressed or not.

**Comment by hvlaardingerbroek** [comment]
Prosaic unit implemented in https://github.com/CambridgeSemiticsLab/nena_corpus/commit/9ffd36ad42c8335b9f4f2938e0ce7b8da23a2c6e
