### ISSUE TITLE
Store 'trailer' feature on word instead of char object

### ISSUE THREAD

**Issue by hvlaardingerbroek** [CambridgeSemiticsLab/nena_tf#6]
The main motivation for making it a feature of `char` is admittedly to accommodate the `T.text` function, which formats the plain text representation of objects in TF (see [here](https://annotation.github.io/text-fabric/Api/Text/)). `T.text` uses the metadata in otext:

```
otext = {
    'fmt:text-orig-full': '{char}{trailer}'
}
```

If we changed it to `{word}{trailer}`, then the `T.text` function call would not work on `char` or `morpheme` objects.

It IS possible to define optional formats, such as:

```
otext = {
     'fmt:char-orig-full:'{char}',
     'fmt:text-orig-full:'{word}{trailer}'
}
``` 
But this means that when you call `T.text(char)` you have to say additionally `fmt='char-orig-full'`.

_Originally posted by @codykingham in https://github.com/CambridgeSemiticsLab/nena_corpus/issues/3#issuecomment-502158064_

**Comment by hvlaardingerbroek** [comment]
There is actually some confusion here, on my part. I am not sure whether `otext` is capable of using objects above slot-level...So where it says `{word}{trailer}`, I am causing some confusion, because "word" implies that is an object. But it seems that `otext` takes **features**, which would mean the slot level may be mandatory...Asking Dirk about that. 

btw, [here is](https://annotation.github.io/text-fabric/Create/CreateTF/) docs for otext feature

_Originally posted by @codykingham in https://github.com/CambridgeSemiticsLab/nena_corpus/issues/3#issuecomment-502160946_

**Comment by hvlaardingerbroek** [comment]
Ok! So we CAN do `char` and `word` formatting differently, which is great actually...

See the documentation [here](https://annotation.github.io/text-fabric/Api/Text/#text-representation)

Also see the [`otext` file](https://github.com/ETCBC/dss/blob/master/tf/0.6/otext.tf) for the DSS corpus. 

In this case, I agree wholeheartedly. `trailer` should be a feature of words only. We need only format the `otext` accordingly. Waiting for details from Dirk.

_Originally posted by @codykingham in https://github.com/CambridgeSemiticsLab/nena_corpus/issues/3#issuecomment-502166220_

**Comment by codykingham** [comment]
Done. Requires the following otext configuration:

```
otext = {
    'sectionTypes': 'dialect,text,line',
    'sectionFeatures': 'dialect,title,number',
    'fmt:text-orig-full': 'morpheme#{text}{trailer}',
    'fmt:text-trans-full': 'morpheme#{trans_f}{trans_trailer_f}',
    'fmt:text-trans-lite': 'morpheme#{trans_l}{trans_trailer_l}',
}
```

T.text now uses morphemes and their trailers to format the text. We must use morpheme trailers, not word trailers, because morphemes occasionally have "-" at their ends. 

NB: `T.text(letter)` will return a blank string since `T.text` now relies on morphemes. To call text features on a letter, simply call `F.text.v(letter)`.
