### ISSUE TITLE
Pipeline with Standard Markdown Sources

### ISSUE THREAD

**Issue by codykingham** [CambridgeSemiticsLab/nena_tf#8]
We need a standard markdown format for representing the source texts from which the Text-Fabric conversion will work. Currently we work from `.docx` files. But later we want to pull from the NENA website database. The TF conversion should work on an identical kind of text format regardless of the original source.

Such a pipeline would work as follows:

original source -> standard markdown -> TF conversion

New transcriptions entered into the website could follow this markdown format. We could use the text-input box by @jamespstrachan, originally designed for paradigm input. Maybe this requires some small modifications to that box?

Having the standard format would allow us to do version control on a "ground truth" text, thus also allowing for a process of correction at the source when necessary.

The markdown standard should be as simple as possible. It should reflect divisions into texts and lines. A concept version is below:

```
# The Monk and the Angel
informant:Yulia Davudi
place:+Hassar +Baba-čanɟa, N

(1) xá-yuma +málla +Nasràdənˈ bərrə̀xšələˈ bəšk̭álələ +k̭usárta déna mən-švàvu.ˈ  màrələˈ hálli xá-dana +k̭usàrtaˈ +báyyən bášlən ɟávo bušàla.ˈ +k̭usárta +ɟúrta lə̀tli.ˈ bəšk̭álolə màyolə +k̭usártaˈ bušála bašùlələ,ˈ labùlolə,ˈ yávolə mə̀drəˈ k̭àˈ švàva.ˈ ʾína tré +k̭usaryay-sùrəˈ mattúyəl ɟàvo.ˈ (2) švàvaˈ màrələˈ ʾáha tré +k̭usaryàtəˈ k̭àm muyyévət?ˈ mə̀rrəˈ +k̭usártət dìyyuxˈ də̀llaˈ tré xínə mə̀nno.ˈ yávəl k̭àtuˈ ʾávət basìma,ˈ bitàyələ.ˈ
```

Where `(1)` encodes a "line", i.e. a verse-like division of the text. This is merely a first concept.

**Comment by hvlaardingerbroek** [comment]
To elaborate a bit on the concept, some more suggestions:

- it should allow marking of foreign words: I suggest markdown's emphasis marker `*`
- it should have markers indicating the language of foreign words: I suggest angle brackets around identifier, like `<R>`
- it should allow a paragraph structure, markdown's empty line should work fine (so a single newline is the same as a space, two newlines is a new paragraph)
- maybe even footnotes -- some markdown extensions allow something like `[^1]`, referring to a later line containing `[^1]: Note text`.

Example:
```
# The Monk and the Angel
informant:Yulia Davudi
place:+Hassar +Baba-čanɟa, N

(1) xá-yuma +málla +Nasràdən| bərrə̀xšələ| bəšk̭álələ +k̭usárta déna mən-švàvu.|
màrələ| hálli xá-dana +k̭usàrta| +báyyən bášlən ɟávo bušàla.|
(2) švàva| *loanword unspecified*[^1] màrələ| ʾáha tré +k̭usaryàtə|
k̭àm muyyévət?| *<E>loanword English<E>* mə̀rrə| +k̭usártət dìyyux|
də̀lla| tré xínə mə̀nno.| yávəl k̭àtu| ʾávət basìma,| bitàyələ.|

(3) *new paragraph* xá-yuma +málla *<E>loanword<E>* +Nasràdən| ...

[^1]: It is unclear from which language the loanword originates.
```

Other features that may be implemented:
- poetry-style newlines that do not mark paragraph endings (maybe `/` or `//`?)
- formal comment notation to e.g. introduce change of speaker (e.g. `(GK: ... )`)

Maybe the text input box could have some extra buttons with diacritics and other exotic characters?

**Comment by hvlaardingerbroek** [comment]
Added file with a draft of the markup specification. Please let me know what you think, if I have overlooked something, etc. See https://github.com/CambridgeSemiticsLab/nena_corpus/commit/3b017122884d9efd6f8e6b159ccab1541c423e7a (in separate branch `tomarkdown`)

**Comment by codykingham** [comment]
This pipeline is now well underway at https://github.com/CambridgeSemiticsLab/nena_corpus
