### ISSUE TITLE
Build Dialect Object

### ISSUE THREAD

**Issue by codykingham** [CambridgeSemiticsLab/nena_tf#9]
There are currently 2 section markers in the corpus: `text_id` and `line`. But several texts have the same `text_id` feature. This causes problems when selecting nodes with a certain reference:

```
T.nodeFromSection(('A36',))
```

This returns only 1 node, despite the fact there are two `A36` texts. 

**Proposal: Introduce a large `dialect` object that will enclose the texts.** `dialect` can then be a sectional feature, so that one can select a given text like this:

```
T.nodeFromSection(('Barwar', 'A36',))
```

Especially since dialects will be used frequently it would be helpful to model them as their own object. We can also annotate dialect objects with features such as coordinates or other useful information.

The database would have the following embedding:

```
dialect
    text
        paragraph
            line
            prosa
                sentence
                    word
                        morpheme
                            char
```

**Comment by hvlaardingerbroek** [comment]
Although originally I thought to record the dialect as main object, I realized that the `text_id`s refer to a specific publication, not a dialect. So far, all available texts of a dialect have been published in one publication, containing texts in one dialect, but will that always be true?

An alternative could be (as suggested in a comment in `generate_TF.ipynb`) to record `publication` as main object, which has as a feature the dialect (or, allowing for multi-dialect publications, we could leave that to `text`).

On the other hand, as long as there is a mechanism to prevent multiple publications of one dialect using the same `text_id`s, I see no problem using `dialect` as main object above `text`, with publication being a feature of `text`.

**Comment by codykingham** [comment]
Indeed this may be an indicator that we ought to prefer `title` over `text_id`, and consider, as you say, that the `text_id` is simply derived from the publication. I expect that a feature like `text_id` may become more and more irrelevant when texts are added from the website. 

So what we could do is a sectioning like this:

> `{dialect}, {title}, {line}`

A stylized version as will be printed through the app would look like this:

> Barwar, The Monk and the Angel, 1

And then, if we have title conflicts we can add version numbers to the title itself as appropriate. e.g. `(2)`

**Comment by hvlaardingerbroek** [comment]
That seems all right. It certainly looks much prettier than e.g. `HOS_Barwar_2008, A1:1`.

**Comment by hvlaardingerbroek** [comment]
But this way, the first text called e.g. `Village life` will stay without number, and from the second one they will be numbered from `Village life (2)` -- as numbering the first one would require renaming it on adding the second one.

Titles need to be unique only within a dialect, so on adding a new source with title `Village life` it needs to be checked with existing titles in the same dialect. But at what stage this should be checked? Upon making the TF resource or the master text? I would say the latter.

**Comment by codykingham** [comment]
Agreed. That is a source text (i.e. master text) issue.

**Comment by codykingham** [comment]
Done. The issue with duplicate titles will need to be solved in the source texts however.
Update: see commit https://github.com/CambridgeSemiticsLab/nena_corpus/commit/327d36ea06e37396d1827e2df8687f20e0c19d81
